apiVersion: v1
kind: ConfigMap
metadata:
  name: ping-pong-config
  namespace: exercises
data:
  HOST: 0.0.0.0
  PORT: "3000"
  PING_PONG_PATH: /pingpong
  PINGS_PATH: /pings
  DB_HOST: ping-pong-postgres-svc
  DB_PORT: "5432"
  DB_NAME: pingpong
  DB_USER: pingpong
  DB_CONNECT_TIMEOUT_SECONDS: "5"
  DB_CONNECT_RETRIES: "30"
  DB_CONNECT_RETRY_DELAY_SECONDS: "2"
