apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-output
  namespace: exercises
spec:
  replicas: 1
  selector:
    matchLabels:
      app: log-output
  template:
    metadata:
      labels:
        app: log-output
    spec:
      securityContext:
        fsGroup: 1000
      volumes:
        - name: shared-log
          emptyDir: {}
        - name: configuration
          configMap:
            name: log-output-config
      containers:
        - name: log-writer
          image: log-output-writer:2.5
          imagePullPolicy: Never
          env:
            - name: LOG_FILE
              value: /usr/src/app/files/log.txt
          volumeMounts:
            - name: shared-log
              mountPath: /usr/src/app/files
        - name: log-reader
          image: log-output-reader:2.5
          imagePullPolicy: Never
          env:
            - name: PORT
              value: "3000"
            - name: LOG_FILE
              value: /usr/src/app/files/log.txt
            - name: PING_PONG_URL
              value: http://ping-pong-svc/pings
            - name: INFORMATION_FILE
              value: /usr/src/app/config/information.txt
            - name: MESSAGE
              valueFrom:
                configMapKeyRef:
                  name: log-output-config
                  key: MESSAGE
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          volumeMounts:
            - name: shared-log
              mountPath: /usr/src/app/files
              readOnly: true
            - name: configuration
              mountPath: /usr/src/app/config
              readOnly: true
