apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-app
  namespace: project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-app
  template:
    metadata:
      labels:
        app: todo-app
    spec:
      securityContext:
        fsGroup: 1000
      volumes:
        - name: image-cache
          persistentVolumeClaim:
            claimName: todo-image-claim
      containers:
        - name: todo-app
          image: todo-app:2.6
          imagePullPolicy: Never
          envFrom:
            - configMapRef:
                name: todo-project-config
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          volumeMounts:
            - name: image-cache
              mountPath: /usr/src/app/files
